apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: redis
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
