apiVersion: v1
kind: Namespace
metadata:
  name: dev

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: django-resource-quota
  namespace: dev
spec:
  hard:
    pods: "10"
    requests.cpu: "3"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi

---
apiVersion: v1
kind: LimitRange
metadata:
  name: django-limit-range
  namespace: dev
spec:
  limits:
    - default:
        cpu: "500m"
        memory: "512Mi"
      defaultRequest:
        cpu: "250m"
        memory: "256Mi"
      type: Container

