# charts/service-c/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.credentials.db }}
  POSTGRES_USER: {{ .Values.credentials.user }}
  POSTGRES_PASSWORD: {{ .Values.credentials.password }}
